# Generated by Django 2.2.4 on 2019-09-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20190902_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
