# Generated by Django 2.2.4 on 2019-09-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_shorurl_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
