# Generated by Django 2.2.4 on 2019-09-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20190903_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
